<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeshCore.Library\MeshCore.Library.csproj" />
  </ItemGroup>
</Project>
