<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <OutputType>WinExe</OutputType>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" />
    <PackageReference Include="MonoGame.Content.Builder.Task" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MeshProps\MeshProps.csproj" />
    <ProjectReference Include="..\MeshRendering\MeshRendering.csproj" />
  </ItemGroup>
</Project>