<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <RollForward>Major</RollForward>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\World.Maps\World.Maps.csproj" />
    <ProjectReference Include="..\Maps.Home\Maps.Home.csproj" />
  </ItemGroup>
</Project>
